# Generated by Django 4.2.5 on 2023-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0006_user_birthday_user_description_user_nationality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followed_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
