# Generated by Django 4.2.5 on 2023-10-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0007_user_followed_by_alter_user_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followed_by",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
