# Generated by Django 4.2.5 on 2023-10-29 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0010_alter_post_timestamp_alter_user_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followed_by",
        ),
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
