# Generated by Django 4.2.5 on 2023-10-29 16:27

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0011_remove_user_followed_by_alter_user_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, default="", max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nationality",
            field=django_countries.fields.CountryField(
                blank=True, default="", max_length=2, null=True
            ),
        ),
    ]
